#!/bin/bash
# 
# Author: Traian Nedelea <tron1point0@gmail.com>
# 
# xinitrc - called by startx for login stuff
# 
# TODO: Test this shit.

# Setup
if [ ! -x /usr/bin/which ]; then
    function which {
        eval "ls {${PATH//:/,}}/autocutsel -f 2>/dev/null"
    }
fi

function can {
    which $1
}

function try {
    can $1 && $*
}

[ -x "$XDG_CONFIG_HOME" ] && export XDG_CONFIG_HOME=$HOME/.config

# Input
try setxkbmap dvorak \
    -option 'compose:ralt' \
    -option 'ctrl:swapcaps' \
    -option 'terminate:ctrl_alt_bksp'

# Graphical
try xsetroot -cursor_name left_ptr
if can feh; then
    [ -r $XDG_CONFIG_HOME/feh/fehbg ] && source $XDG_CONFIG_HOME/feh/fehbg
    [ -r $HOME/.fehbg ] && source $HOME/.fehbg
fi
RES=$XDG_CONFIG_HOME/xorg/xresources [ -r "$RES" ] && xrdb "$RES"

# Apps
try autocutsel &
#try jackd --no-realtime --no-mlock --port-max 256 --driver alsa \
#    --duplex --hwmeter --hwmon --inchannels 2 --outchannels 2 &
try conky &
try xscreensaver -no-splash &
try dropboxd &

# Window Manager
LOG_DIR=$HOME/.log
LOG_FILE=$LOG_DIR/xorg.log
[ ! -d $LOG_DIR ] && mkdir -p $LOG_DIR

try xrandr --output VGA1 --left-of DVI1 &

can compiz && exec compiz ccp &> $LOG_FILE
can enlightenment_start && exec enlightenment_start &> $LOG_FILE
can fluxbox && exec fluxbox &> $LOG_FILE
try cairo-compmgr &
can xmonad && exec xmonad &> $LOG_FILE
can twm && exec twm &> $LOG_FILE
can xterm && exec xterm &> $LOG_FILE
