#!/bin/bash
# 
# Author: Traian Nedelea (tron1point0@gmail.com)
# Version: 1.0
# Last Modified: 2011-03-29
# 
# Change Log:
# 
# Allows you to use the XDG spec and plugins for your bash configs.

# Use sane defaults
[ -z $XDG_CONFIG_HOME ] && XDG_CONFIG_HOME=$HOME/.config
export BASH_CONFIG_DIR=$XDG_CONFIG_HOME/bash
export BASH_PLUGIN_DIR=$BASH_CONFIG_DIR/plugins

source <(cat $BASH_PLUGIN_DIR/*)

# Last
[ -n "$PS1" ] && type -P fortune &>/dev/null && fortune -a
